icons_format = "{icon}"

[theme]
theme = "ctp-macchiato"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"

[[block]]
block = "sound"

[[block]]
block = "hueshift"
hue_shifter = "wlsunset"
step = 50
click_temp = 2500
format = "\uf185 $temperature"

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "kdeconnect"
format = " $icon {$bat_icon $bat_charge |}{$notif_icon |}{$network_icon$network_strength $network_type |}"
bat_good = 101

[[block]]
block = "time"
interval = 60
